#!/bin/bash
#
# Copyright © 2020 Filip Paskali
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# list divices by:
# pactl list short sinks | awk '{print $2}'
DEV_NAME=alsa_input.usb-V_NO_NO_NONE_Fantech_Leviosa-00.mono-fallback

LIST=$(pactl list | grep -A 6 "$DEV_NAME")
DEV_DESC=$(echo "$LIST" | awk -F ': ' '/Description/ {print $2; exit}')
DEV_STAT=$(echo "$LIST" | awk '/Mute/ {print $2; exit}')
MATERIAL=$HOME/.local/share/icons/material

case $1 in
	toggle) pactl set-source-mute "$DEV_NAME" toggle ;;
	mute) pactl set-source-mute "$DEV_NAME" 0 ;;
	unmute) pactl set-source-mute "$DEV_NAME" 1 ;;
esac

case $DEV_STAT in
  no)
    dunstify -r 9991 "Muted" "$DEV_DESC" -i $MATERIAL/mic-off.svg
    ;;
  yes)
    dunstify -r 9991 "Unmuted" "$DEV_DESC" -i $MATERIAL/mic.svg
    ;;
esac
