#!/bin/bash

FADEIN="/home/ali/.local/scripts/mpd-fadein"
FADEOUT="/home/ali/.local/scripts/mpd-fadeout"

STATE=$(mpc status | head -2 | tail -1 | awk '{print $1}' | tr -d '[]')

if [ "$STATE" = "playing" ]; then
  "$FADEOUT"
else
  "$FADEIN"
fi
