#!/usr/bin/python3

import requests
from bs4 import BeautifulSoup

def main():
    URL = "https://almanar.com.lb/legacy/salat.php"
    headers = {'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0'}
    try:
        page = requests.get(URL, headers=headers)
    except:
        return "network error"
    soup = BeautifulSoup(page.content, "html.parser")
    times = soup.find("div", class_="prayer-times")

    def get_names():
        rights = times.find_all("div", class_="m-right")
        lefts = times.find_all("div", class_="m-left")

        for i in range(len(rights)):
            print(f"{lefts[i].text.strip()} : {rights[i].text.strip()}")
    get_names()

if __name__ == "__main__":
    main()
