#!/usr/bin/env perl
#
# Copyright (C) 2018-2021 James Murphy, Falko Galperin
# Licensed under the terms of the GNU GPL v2 only.
#
# i3blocks blocklet script to play youtube videos from your clipboard using mpv

use strict;
use warnings;
use utf8;
use Data::Validate::URI;

my $signal = $ENV{signal} || 1;
my $notify_i3bar = "pkill -RTMIN+$signal i3blocks";
my $string = qx/xclip -out/;
$string =~ s/[';\\]//g; # remove characters that can cause i3-msg to crash
my $uriValidator = new Data::Validate::URI();
my $BLOCK_BUTTON = $ENV{BLOCK_BUTTON} || 0;
my $USER = $ENV{USER};
my $i3cmd = "";
my $i3cmdexitstatus = 0;

if ($uriValidator->is_web_uri($string) or $BLOCK_BUTTON == 3) {
    if ($BLOCK_BUTTON == 1) {
        $i3cmd = "exec --no-startup-id mpv --ytdl --ytdl-format=bestvideo[height=480]+bestaudio --tls-verify '$string' && $notify_i3bar";
    } elsif ($BLOCK_BUTTON == 3) {
        $i3cmd = "exec --no-startup-id mpv --no-video --ytdl --tls-verify --ytdl-format=bestaudio '$string' && $notify_i3bar";
    } elsif ($BLOCK_BUTTON == 2) {
        $i3cmd = "exec --no-startup-id killall -u $USER mpv && $notify_i3bar";
    }

    system("i3-msg", "-q", $i3cmd);
    # i3-msg may return before mpv has started
    sleep(.1);
}

binmode(STDOUT, ":utf8");
print("<span>\x{f16a}</span>\n");
